theme: jekyll-theme-merlot
title: Let me secure that for you!
tagline: How to use Virtual Patching to protect your site
author :
  name : Kirk Jackson
  email : kirk@pageofwords.com
  github : lmstfu
  twitter : letmesecurethat
