theme: jekyll-theme-slate
title: Let me secure that for you!
description: How to use Virtual Patching to protect your site
author :
  name : Kirk Jackson
  github : lmstfu
  twitter : letmesecurethat
